from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from tasks.views import (
    admin_processes,
    board_snapshot,
    bulk_delete_tasks,
    create_task,
    delete_employee_account,
    delete_task_attachment,
    delete_task_template,
    dismiss_completed_task,
    delete_task,
    delete_employee_profile_photo,
    delete_own_account,
    delete_profile_photo,
    employee_account,
    employee_assign_task,
    employee_detail,
    employee_directory,
    delete_task_message,
    edit_profile,
    edit_task,
    post_task_message,
    register_user,
    task_board,
    task_detail,
    task_list_page,
    task_snapshot,
    task_wall,
    toggle_subtask,
    toggle_task,
    update_employee_profile_photo,
    update_profile_photo,
    update_task_message,
    update_task_status,
    user_profile,
    site_updates_page,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', task_board, name='home'),
    path('tasks/list/', task_list_page, name='task_list_page'),
    path('wall/', task_wall, name='task_wall'),
    path('updates/', site_updates_page, name='site_updates_page'),
    path('processes/', admin_processes, name='admin_processes'),
    path('employees/', employee_directory, name='employee_directory'),
    path('employees/<int:user_id>/', employee_detail, name='employee_detail'),
    path('employees/<int:user_id>/assign-task/', employee_assign_task, name='employee_assign_task'),
    path('employees/<int:user_id>/account/', employee_account, name='employee_account'),
    path('employees/<int:user_id>/account/delete/', delete_employee_account, name='delete_employee_account'),
    path('employees/<int:user_id>/photo/', update_employee_profile_photo, name='update_employee_profile_photo'),
    path(
        'employees/<int:user_id>/photo/delete/',
        delete_employee_profile_photo,
        name='delete_employee_profile_photo',
    ),
    path('api/board/', board_snapshot, name='board_snapshot'),
    path('api/task/<int:task_id>/', task_snapshot, name='task_snapshot'),
    path('create/', create_task, name='create_task'),
    path('profile/', user_profile, name='profile'),
    path('profile/delete/', delete_own_account, name='delete_own_account'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('profile/photo/', update_profile_photo, name='update_profile_photo'),
    path('profile/photo/delete/', delete_profile_photo, name='delete_profile_photo'),
    path(
        'profile/password/',
        auth_views.PasswordChangeView.as_view(
            template_name='tasks/account/change_password.html',
            success_url=reverse_lazy('profile'),
        ),
        name='change_password',
    ),
    path('task/<int:task_id>/', task_detail, name='task_detail'),
    path('task/<int:task_id>/messages/', post_task_message, name='post_task_message'),
    path('task/<int:task_id>/messages/<int:message_id>/edit/', update_task_message, name='update_task_message'),
    path('task/<int:task_id>/messages/<int:message_id>/delete/', delete_task_message, name='delete_task_message'),
    path('attachments/<int:attachment_id>/delete/', delete_task_attachment, name='delete_task_attachment'),
    path('templates/<int:template_id>/delete/', delete_task_template, name='delete_task_template'),
    path('task/<int:task_id>/status/', update_task_status, name='update_task_status'),
    path('task/<int:task_id>/dismiss/', dismiss_completed_task, name='dismiss_completed_task'),
    path('edit/<int:task_id>/', edit_task, name='edit_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
    path('delete-selected/', bulk_delete_tasks, name='bulk_delete_tasks'),
    path('toggle/<int:task_id>/', toggle_task, name='toggle_task'),
    path('toggle_sub/<int:subtask_id>/', toggle_subtask, name='toggle_subtask'),
    path('login/', auth_views.LoginView.as_view(template_name='tasks/auth/login.html'), name='login'),
    path('register/', register_user, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
