TEMPLATE_PATHS = {
    'dashboard': 'tasks/index.html',
    'admin_processes': 'tasks/admin/processes.html',
    'site_updates': 'tasks/updates.html',
    'auth_login': 'tasks/auth/login.html',
    'auth_register': 'tasks/auth/register.html',
    'profile': 'tasks/account/profile.html',
    'edit_profile': 'tasks/account/edit_profile.html',
    'change_password': 'tasks/account/change_password.html',
    'employee_directory': 'tasks/employees/index.html',
    'employee_detail': 'tasks/employees/detail.html',
    'employee_assign_task': 'tasks/employees/assign_task.html',
    'employee_account': 'tasks/employees/account.html',
    'task_detail': 'tasks/task/detail.html',
    'task_form': 'tasks/task/form.html',
    'task_list': 'tasks/task/list.html',
    'task_wall': 'tasks/task/wall.html',
}
