# Generated by Django 6.0.3 on 2026-03-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_assignment_statuses(apps, schema_editor):
    EmployeeProfile = apps.get_model('tasks', 'EmployeeProfile')
    Task = apps.get_model('tasks', 'Task')
    TaskAssignmentStatus = apps.get_model('tasks', 'TaskAssignmentStatus')

    EmployeeProfile.objects.filter(status='blocked').update(status='paused')

    through_model = Task.assigned_users.through
    shared_map = {}
    for task_id, user_id in through_model.objects.values_list('task_id', 'user_id'):
        shared_map.setdefault(task_id, []).append(user_id)

    for task in Task.objects.all().iterator():
        participant_ids = []
        if task.assigned_to_id:
            participant_ids.append(task.assigned_to_id)
        participant_ids.extend(shared_map.get(task.id, []))

        seen_ids = set()
        for user_id in participant_ids:
            if user_id in seen_ids:
                continue
            seen_ids.add(user_id)
            TaskAssignmentStatus.objects.get_or_create(
                task_id=task.id,
                user_id=user_id,
                defaults={
                    'status': task.status,
                    'completed_at': task.completed_at if task.status == 'completed' else None,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskAssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_statuses', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_task_assignment_status')],
            },
        ),
        migrations.RunPython(populate_assignment_statuses, migrations.RunPython.noop),
    ]
