# Generated by Django 6.0.3 on 2026-03-25 12:05

from django.conf import settings
from django.db import migrations, models


def set_site_owner(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    EmployeeProfile = apps.get_model('tasks', 'EmployeeProfile')

    for user in User.objects.filter(is_superuser=True):
        EmployeeProfile.objects.get_or_create(user=user)

    owner_user = User.objects.filter(is_superuser=True).order_by('id').first()
    if not owner_user:
        return

    EmployeeProfile.objects.filter(is_site_owner=True).exclude(user=owner_user).update(is_site_owner=False)
    EmployeeProfile.objects.filter(user=owner_user).update(is_site_owner=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_site_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_site_owner, migrations.RunPython.noop),
    ]
