# Generated by Django 6.0.3 on 2026-03-27 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_employeeprofile_is_site_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeactivity',
            index=models.Index(fields=['profile', '-created_at'], name='tasks_emplo_profile_0384b8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_site_owner'], name='tasks_emplo_is_site_8ba4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed', 'deadline'], name='tasks_task_is_comp_6474e1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline', '-created_at'], name='tasks_task_deadlin_993ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentstatus',
            index=models.Index(fields=['status', '-updated_at'], name='tasks_taska_status_a06f76_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmessage',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taskm_task_id_017c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmessage',
            index=models.Index(fields=['created_at'], name='tasks_taskm_created_610705_idx'),
        ),
    ]
