# Generated by Django 6.0.3 on 2026-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_employeeactivity_tasks_emplo_profile_0384b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
    ]
