# Generated by Django 6.0.3 on 2026-04-17 08:20

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplateSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='activity_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='generated_for_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedTaskFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('page', models.CharField(choices=[('list', 'Task list'), ('board', 'Board'), ('wall', 'Wall')], default='list', max_length=20)),
                ('query', models.CharField(blank=True, max_length=200)),
                ('board_filter', models.CharField(default='all', max_length=20)),
                ('priority_filter', models.CharField(default='all', max_length=20)),
                ('view_mode', models.CharField(default='list', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_task_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks.models._task_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskmessage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('deadline_offset_days', models.PositiveIntegerField(default=0)),
                ('recurrence', models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_for', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_as_owner', to=settings.AUTH_USER_MODEL)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='task_templates_as_participant', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.tasktemplate'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_template', 'generated_for_date'], name='tasks_task_source__49830f_idx'),
        ),
        migrations.AddField(
            model_name='tasktemplatesubtask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.tasktemplate'),
        ),
        migrations.AddIndex(
            model_name='savedtaskfilter',
            index=models.Index(fields=['user', 'page'], name='tasks_saved_user_id_7ebb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', 'created_at'], name='tasks_taska_task_id_3aa34c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['message', 'created_at'], name='tasks_taska_message_d5917c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskauditlog',
            index=models.Index(fields=['task', '-created_at'], name='tasks_taska_task_id_99b479_idx'),
        ),
        migrations.AddIndex(
            model_name='taskauditlog',
            index=models.Index(fields=['-created_at'], name='tasks_taska_created_7665a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['is_active', 'recurrence'], name='tasks_taskt_is_acti_0e3973_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['-updated_at'], name='tasks_taskt_updated_bfa7b6_idx'),
        ),
    ]
