# Generated by Django 6.0.3 on 2026-04-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_tasktemplatesubtask_employeeprofile_activity_seen_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='activity_seen_at',
        ),
    ]
