# Generated by Django 6.0.3 on 2026-04-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_employeeprofile_status_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='savedtaskfilter',
            name='tasks_saved_user_id_7ebb5e_idx',
        ),
        migrations.DeleteModel(
            name='SavedTaskFilter',
        ),
    ]
